### ISSUE TITLE
Actual test and whole for loop very likely to just get optimized away by jvm

### ISSUE THREAD

**Issue by Janmm14** [amnoah/Minecraft-Server-Benchmark#4]
Because the result of Math.hypot is not being used.

**Comment by amnoah** [comment]
So far this has not been the case, but I have been meaning to rewrite the Test case anyways.
Currently the implementation is rather lazy, running a simple test millions of times, and I'd prefer to rather create a complex test which can be run less.

**Comment by amnoah** [comment]
Can you confirm whether the issue still stands after [19024e1](https://github.com/amnoah/Minecraft-Server-Benchmark/commit/19024e17dc8ee45c4cc746d7d450228897cd0ef2)?

**Comment by amnoah** [comment]
Closing the ticket, please reopen it if the issue still stands.
